### ISSUE TITLE
Add ensure_newline_at_eof_on_save option

### ISSUE THREAD

**Issue by tomdxw** [dxw/dotfiles#1]
When Sublime Text users accidentally remove newlines from the ends of files vim has to add those newlines back in. So this would also help prevent modifying files needlessly.

**Comment by dgmstuart** [comment]
I never understood why vim does that. Now I do, though it seems a little arcane: https://stackoverflow.com/questions/729692/why-should-files-end-with-a-newline

Is there any valid argument that vim adding them is a needless change? ;)
Seriously though: would adding this in be problematic because lots of pages would have this additional change next time they're saved?

The setting is `"ensure_newline_at_eof_on_save": true`

**Comment by tomdxw** [comment]
> Now I do, though it seems a little arcane:

If you use almost any modern shell (except zsh), you still get that issue with cat messing up your prompt.

> Seriously though: would adding this in be problematic because lots of pages would have this additional change next time they're saved?

At least in the WordPress projects, I think files without a trailing newline are in the minority. If we're going to introduce one change that'll cause additional changes (trim_trailing_white_space_on_save) then we may as well add this one at the same time to minimise disruption.

**Comment by dgmstuart** [comment]
Fixed in ad30d2008cccb7324cf92af5ee85ccd5c2094a00
